xrdb /home/mike/.Xresources
xbindkeys
xmodmap -e "keycode 108 = Super_L" # Reassign Alt_R to Super_L
xmodmap -e "remove mod1 = Super_L" # Make sure X keeps it out of mod1 group

# Sreen saver
xset dpms 180 &
xss-lock -- slock -m "Enter password" &

xbacklight -set 1

exec awesome
